default:
  min: 7
  max: 31
  current: 0
cold:
  min: -10
  max: 5
  current: 0
hot:
  min: 33
  max: 50
  current: 0
murder-snow:
  min: -50
  max: -5
  current: 0
nether:
  min: 49
  max: 80
  current: 0
scorched-earth:
  min: -10
  max: 60
  current: 0
end:
  min: -70
  max: -30
  current: 0
corruption:
  min: -35
  max: 120
  current: 0