# Config Cath.HCSYS
# Legt fest, ab welchen Wert welche Effekte auftreten
effect:
  light: 65
  medium: 75
  high: 90
# Legt den Maximalen Spieler Wert an, bevor er Schaden erleidet
player-max: 100

# Legt und speichert Temperatur Werte an.
default:
  min: 7
  max: 31
  current: 0
murder-snow:
  min: -50
  max: -5
  current: 0
nether:
  min: 49
  max: 80
  current: 0
sb-nether:
  min: 49
  max: 80
  current: 0
sb-scorched:
  min: -10
  max: 60
  current: 0
sb-xmas:
  min: -30
  max: 1
  current: 0
sb-corrupt:
  min: -35
  max: 120
  current: 0
end:
  min: -70
  max: -30
  current: 0
...